### ISSUE TITLE
`Error in if (type == "array") { : argument is of length zero`

### ISSUE THREAD

**Issue by baslat** [prestodb/RPresto#176]
I upgraded to the GitHub version of {RPresto} (from the CRAN version) because of this warning:

```
Warning message:
<PrestoConnection> uses an old dbplyr interface
```

Upgrading silenced that warning, however when I now receive the following error:

```R
r$>  dplyr::tbl(presto, "table_name")
Error in if (type == "array") { : argument is of length zero
```

This does not happen with the CRAN version. The table I am trying to connect to has array columns. 

For now I will continue to use the CRAN version, however I wanted to bring this to you attention.

**Comment by jarodmeng** [comment]
Thanks for the bug report! I suspect that the table you're using has some columns of unsupported data types. Can you let me know what column types your table has?

**Comment by baslat** [comment]
There are the following column types:

- timestamp(3)
- double
- bigint
- array(varchar)
- array(bigint)
- integer
- array(row(varchar, double))

**Comment by jarodmeng** [comment]
All of those data types should be supported and they are tested. So it will need a bit more investigation to pinpoint why the bug occurs.

2 Questions:
1. What's the connector you're using?
2. What does the "3" in "timestamp(3)" mean?

To troubleshoot effectively, I will need to reproduce the error. If there's anything that you can provide (e.g. a sample data file, etc) to help debug, it would be appreciated.

**Comment by baslat** [comment]
I'll do what I can re reprex, but it might take me a bit to sanitise it though.

1. Is this what you meant?
```R
presto <- DBI::dbConnect(
    RPresto::PResto(), 
    use.trino.headers = TRUE,
    schema = "my_schema", 
    user = "my_user", 
    catalog = "hive",
    parameters = list(hive.parquet_use_column_names = TRUE))

dplyr::tbl(presto, "table_name")
```


2. I'm not an SQL expert, but [according to this](https://stackoverflow.com/questions/49286052/is-there-any-difference-between-timestamp3-timestamp) it looks like it is millisecond precision.

**Comment by jarodmeng** [comment]
I see that `TIMESTAMP(P)` is a specific data type that Trino has (see [link](https://trino.io/docs/current/language/types.html#timestamp-p)). But I manage to run a simple query on it and it doesn't seem to be causing any problems.

``` r
con.trino <- DBI::dbConnect(
  drv = RPresto::Presto(),
  host = "http://localhost",
  port = 8090,
  user = Sys.getenv("USER"),
  catalog = "memory",
  schema = "default",
  use.trino.headers = TRUE
)
DBI::dbGetQuery(
  con.trino,
  "SELECT CAST(TIMESTAMP '2020-06-10 15:55:23.383345' AS TIMESTAMP(3)) AS ts"
)
#> # A tibble: 1 × 1
#>   ts                 
#>   <dttm>             
#> 1 2020-06-10 15:55:23
```

<sup>Created on 2022-09-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

If you can narrow down the bug to a particular column, it would be helpful to narrow down the possibilities.

**Comment by jarodmeng** [comment]
I managed to reproduce the error.

``` r
con.trino <- DBI::dbConnect(
  drv = RPresto::Presto(),
  host = "http://localhost",
  port = 8090,
  user = Sys.getenv("USER"),
  catalog = "memory",
  schema = "default",
  use.trino.headers = TRUE
)
RPresto:::create_primitive_arrays_table(con.trino, time_zone = "-08:00")
#> The previous table presto_primitive_arrays has been dropped.
#> The table presto_primitive_arrays has been created.
tbl.x <- dplyr::tbl(con.trino, "presto_primitive_arrays")
#> Error in if (type == "array") {: argument is of length zero
```

<sup>Created on 2022-09-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

The same code runs fine on a Presto server, so I suspect that it's caused by some differences between Presto and Trino. I will investigate a bit more and issue a hotfix patch.

**Comment by jarodmeng** [comment]
@baslat I managed to debug and figure out the reason behind the bug. Although Trino and Presto communicate the result data in the same list format, the schema info JSONs are packaged differently. The new RPresto (1.4.0) we're developing is able to handle all primitive and complex (i.e. ARRAY, MAP, and ROW) because we did a major refactoring of the translation code to use the schema info (the code in the CRAN version, 1.3.8, doesn't utilize the schema, only the data). This difference between Trino and Presto and the fact that our code now uses the schema cause the bug.

I've created a PR (#181) to make the translation code compatible with Trino and modified our unit testing to make sure that Trino compatibility is tested.

Can you help verify that the PR actually fixes your problem?

You can get the hotfix version of RPresto using

```
devtools::install_github("jarodmeng/RPresto", ref = "hotfix_trino")
```

You can always revert it back to the CRAN version (via `install.packages()`) later.

Let me know if the hotfix works and I will publish the PR. Thanks!

**Comment by baslat** [comment]
Nice work @jarodmeng! I tested the branch and it has fixed the original error. However, it introduces a new error related to 64-bit integers.

In the CRAN version I get the following warning:
```
In .json.tabular.to.data.frame(data.list, r.types, timezone = timezone) :
  integer columns [9, 24, 32, 44, 52] are cast to double since R does not have full support for 64-bit integers. 
```
and the columns contain values (doubles).

In the branch version I get
```
Warning messages:
1: In as.integer.integer64(x) : NAs produced by integer overflow
2: In as.integer.integer64(x) : NAs produced by integer overflow
3: In as.integer.integer64(x) : NAs produced by integer overflow
4: In as.integer.integer64(x) : NAs produced by integer overflow
5: In as.integer.integer64(x) : NAs produced by integer overflow
```
and the columns in question are just`NA`.

Could the `{bit64}` package help here perhaps?

**Comment by jarodmeng** [comment]
@baslat This is intentional. You can use the `bigint` argument to control how RPresto translates `BIGINT` into R.
* `bigint = "numeric"` translates `BIGINT` into `double` in R.
* `bigint = "character" translates `BIGINT` into `character` in R.
* `bigint = "integer64" uses `bit64` to translate `BIGINT` to `bit64::integer64` in R.
* The default setting is `bigint = "integer"` which translates `BIGINT` to `integer`. This is set as the default to be consistent with other DBI package and because most `BIGINT` numbers can be converted to 32-bit integer.

You can set the `bigint` argument in 2 ways, with different scope.
* Pass `bigint` argument to `dbConnect()` when you create the connection. In this way, all transactions using the connection will use the new setting. This has the largest scope.
* Pass `bigint` to `dbGetQuery()` (if you're using the DBI interface) or `collect()` (if you're using the dplyr interface). This setting is only effective for the one API call (it doesn't change the underlying connection object). It offers more flexibility to the user's workflow.

Hope this is helpful.

**Comment by baslat** [comment]
Oh haha, well that's good to know!

I tested your branch with `bigint = "integer64"` in `DBI::dbConnect()` and all seems to be working now. Thanks for your responsiveness!
