### ISSUE TITLE
Reference classes?

### ISSUE THREAD

**Issue by Ironholds** [prestodb/RPresto#2]
Hey! What would you think of swapping out the internal reference classes for R6 classes? They achieve the same ends but are more performant - see [this vignette](http://cran.r-project.org/web/packages/R6/vignettes/Performance.html)

**Comment by cosinequanon** [comment]
Are there any major benefits other than performance? I think for our use case the run time is completely dominated by the time Presto takes and the time to parse the data.

**Comment by Ironholds** [comment]
Smaller memory footprint, and more granularity in private-versus-public members are my draw, but yeah, they may not be applicable :)

**Comment by dain** [comment]
Wow.  If I'm reading that correctly it uses about half the memory and is 6x faster at creating object.  That should dramatically speed up the decoding time of the presto results, and allow for larger result sets.  I expect that this could increase query latency for small queries or fast stores like Raptor, because of how the Presto statement protocol is shaped.  For queries with large result sets, the fetching of result data can be dominated by client decode time, since most clients are single threaded.

**Comment by Ironholds** [comment]
The syntax is also pretty trivial similar (easier than the S3/S4 switch, imo); I'm happy to take the lead on branching and rewriting around R6 classes, if people think a switch would be helpful?

**Comment by cosinequanon** [comment]
I believe only reference class we use is PrestoCursor, everything else is S3/S4. Is this the part you want to rewrite? The rest of the code needs to comply with the DBI interface. I'm certainly not opposed to using R6, I just want to make sure the effort is justified.

**Comment by Ironholds** [comment]
Indeedy; you know the internal structure better than me, so if the package would benefit from PrestoCursor having smaller creation times/memory footprints, let me know. If not it probably doesn't justify the work, yeah.

**Comment by cosinequanon** [comment]
The only things stored in PrestoCursor are things we need to be stateful such as the next.uri, current stats, etc. and they are all of a relatively small size. It would be interesting to see what the difference is in performance and memory usage but I have a feeling the change will be very small. We wouldn't add an extra dependency unless there was a material benefit.

**Comment by Ironholds** [comment]
Makes sense! Okay; will call it closed, then :)
