### ISSUE TITLE
dbSendQuery not the same as dbGetQuery

### ISSUE THREAD

**Issue by jeffwong** [prestodb/RPresto#21]
I am getting different results for dbSendQuery(con, <sql string>) compared to dbGetQuery. When querying for 10k rows dbGetQuery gives me the exact right dataset back, but dbSendQuery sometimes gives me 10k rows and sometimes gives me ~300 rows.

**Comment by onurfiliz** [comment]
@jeffwong that is the expected behavior. dbGetQuery always fetches the full result set, but the dbSendQuery/dbFetch pair should be used in a loop with dbHasCompleted as in https://github.com/prestodb/RPresto/blob/master/R/dbFetch.R#L64-L75. If you'd like to fetch the full result set with dbSendQuery, you should use dbFetch(result, -1). 

Sorry about the ambiguity, we'll document this behavior more clearly in the dbFetch implementation docs.
