### ISSUE TITLE
Unable to connect to Starburst Galaxy

### ISSUE THREAD

**Issue by rparrish** [prestodb/RPresto#273]
Using RPresto 1.4.6 on R 4.4.1, I’m getting a 401 authentication error using this snippet to connect to a Free Cluster on Starburst Galaxy:

```
con <- DBI::dbConnect(
    drv = RPresto::Presto(),
    host = Sys.getenv("TRINO_HOST"),
    port = 443,
    user = Sys.getenv("TRINO_USER"),
    password = Sys.getenv("TRINO_PASSWORD"),
    catalog = "sample",
    schema = "demo")
```

I’m able to successfully connect via Trino CLI using the same environment variables and from DBeaverCE.

Any suggestions or alternative ways to connect to Starburst Galaxy from R would be greatly appreciated

**Comment by willshen99** [comment]
Hi @rparrish 
We ran into same error when connecting to Trino on our own server. It turned out to be authentication issue. The authentication can be configured using `httr::set_config()`. We fixed our error by running below:
```
httr::set_config(
  httr::config(
    httpauth=1,
    userpwd='{user}:{password}',
    ssl_verifypeer=0
  )
)
```

On alternative ways: Starburst provides a free [ODBC driver](https://docs.starburst.io/clients/odbc.html) to connect to Starburst products. It's possible you use odbc package to connect (see more info [here](https://solutions.posit.co/connections/db/r-packages/odbc/)).

**Comment by rparrish** [comment]
Thanks @willshen99. That helped and I was able to connect using Rpresto using your suggestion. I'm hopeful that I can get ODBC set up as well later but want to focus on some proof of concepts and patterns during the remainder of the free trial period.
