### ISSUE TITLE
R client much slower than Python client

### ISSUE THREAD

**Issue by jeffwong** [prestodb/RPresto#33]
Hi, I found a python client for Presto at

https://github.com/easydatawarehousing/prestoclient/blob/master/python/prestoclient.py

On a table with 1.7 million rows this client is much faster than RPresto. Digging around the code base I found dbFetch is implemented slightly inefficiently in https://github.com/prestodb/RPresto/blob/master/R/dbFetch.R

The R function creates an empty data frame, and then loops through the result set calling 'rbind'. This is slow because R will allocate memory for the new rv data frame, and then on the next iteration it will resize etc. It's easier to store the results in a list, and then use do.call('rbind', rv) at the end to collapse the results into 1 data frame.

dbBigQuery = function(con, sql) {
  send = dbSendQuery(con, sql)
  results = list()
  counter = 1
  while (!dbHasCompleted(send)) {
    tryCatch({
      chunk <- dbFetch(send)
      print (sprintf("downloaded %s rows", nrow(chunk)))
      results[[counter]] = chunk
      counter = counter + 1  
    }, error = function(e) {
      message("encountered error: will skip this check and continue downloading results")
      message(e)
    })
  }
  return (do.call('rbind', results))
}

After this simple speedup I got results from my 1.7M row table in 12-13 mins instead of 15. However, if I were to use the Python client and dump the result to a text file for R read in, I can get the results in < 5 mins. Why is the Python client so much faster? They are both hitting the  <host>/v1/statement endpoint

The python client hasn't been maintained for over a year, but still seems to work. Wondering if it's a smarter strategy for the RPresto library to just wrap the python client? Would this be a solution you are willing to adopt ?

**Comment by cosinequanon** [comment]
Yes, it is a known issue that RPresto is slow for large amounts of data. We should probably spend some time optimizing it but haven't gotten around to it. Internally at Facebook we shell out to the CLI, write to a temp file and read it back in when we know there will be a lot of rows returned. This isn't very efficient on small queries because you incur the JVM startup time when launching the CLI, it also has the downside that types are not preserved.

Your code doesn't look like it works as is, you initialize the variable `counter` that you never increment nor do you use it. Are you sure you are getting the expected results? I did some benchmarking previously comparing using `rbind` on each iteration versus appending to a list and then calling `do.call` but I did not see any difference in performance between the two methods. (Maybe I didn't benchmark on large enough data? I suppose it is worth revisiting if you are seeing the improvement you claim.)

I don't think we will ever wrap the python client, the goal of this project is to have native R support. Instead we would prefer to improve the performance of the current package using only R (with the possible exception of Rcpp).

**Comment by jeffwong** [comment]
Edited to fix the code. The CLI strategy makes sense to me and the concern of JVM startup time also makes sense. +1 for Rcpp, looking forward to it. I will use this for small queries and find another way for big queries

**Comment by onurfiliz** [comment]
@jeffwong thanks for your analysis and feedback. To add to @cosinequanon 's points, correctness and type safety has been our initial focus before speed, so I wouldn't be surprised if we are inefficient. Note that the python client you have pointed out directly converts json to python, so it will not have support for many data types out of the box. I haven't run tests, but it's possible python's json deserializer is faster than jsonlite too. That said, in our tests RPresto was faster up to 100k rows compared to the "shelling out to CLI" method @cosinequanon mentioned.
As for wrapping the python client, in addition to @cosinequanon's point, we prefer to stick with a pure R solution as much as possible since marshaling from python probably would kill all the speed benefits. It would also make installation considerably harder.

**Comment by cosinequanon** [comment]
@jeffwong #37 makes the change you suggested with `rbind`

**Comment by cosinequanon** [comment]
And #38 makes things faster if you have dplyr installed
