### ISSUE TITLE
Support for LDAP Authentication and SSL Path

### ISSUE THREAD

**Issue by chadwn** [prestodb/RPresto#83]
I'm attempting to login into a db however it requires additional parameters to be passed to the header.  Currently I'm just getting an "Empty reply from server" error.  I tried using the parameters argument to pass the following parameters but was unsuccessful.

AuthenticationType
SSLTrustStorePath
SSLTrustStorePwd
AllowSelfSignedServerCert

Also please excuse my ignorance!

**Comment by onurfiliz** [comment]
Could you expand on it a bit more? Which backend is this for, e.g. hive, mysql, postgresql? If these are supposed to be passed in the request headers, we currently don't have a mechanism to do so. But we would consider adding it if needed.

**Comment by electrum** [comment]
There are two independent things needed from the client:

* Support for configuring the SSL trust store, or the "CA cert bundle" as libcurl calls it. See [CURLOPT_CAINFO](https://curl.haxx.se/libcurl/c/CURLOPT_CAINFO.html) and [CURLOPT_CAPATH](https://curl.haxx.se/libcurl/c/CURLOPT_CAPATH.html).
* Support for [basic authentication](http://httr.r-lib.org/reference/authenticate.html), which is what LDAP uses. Note that the client should refuse to use this if not configured for HTTPS, as the password is sent in the clear with basic auth.

**Comment by electrum** [comment]
Note that LDAP is a detail of the server configuration. From the client's point of view, this is simply "password" authentication and should be named as such. Once https://github.com/prestodb/presto/pull/9865 is merged, the server will support pluggable authenticators for passwords, and LDAP will simply be a plugin that is configured.

**Comment by onurfiliz** [comment]
Oh, I see. Then, the following could work as a workaround until we add support:

    httr::set_config(
      httpauth=1,
      userpwd='username:password',
      ssl.verifypeer=0,
      cainfo='...',
      capath='...'
    )
    con <- DBI::dbConnect(RPresto::Presto(), ...)
    ...

Alternatively, you can use `httr::with_config` and wrap every `DBI::` call, if you are averse to global state. Note that this is untested code since I'll have to do some work to prepare a setup environment.

**Comment by chadwn** [comment]
I attempted the workaround but was unsuccessful.  It is responding with Unknown option: ssl.verifypeer

**Comment by onurfiliz** [comment]
@dvanlunen, are you using 'http://' instead of 'https://' in your host by any chance?

I have considered this issue more, and I think letting httr handle the authentication with the provided config mechanism is the way to go. Trying to support it from RPresto will just mirror the httr/curl API. Please feel free to reopen if you disagree.

**Comment by yutannihilation** [comment]
@onurfiliz 
I don't think it's not secure to set `userpwd` globally as it will be added to every requests, which means the user might send the credential to other websites. Besides, the global setting is also not very convenient in cases when other service requires differently (e.g. different `cainfo`).

So, I believe it's nice if `RPresto` stores the settings like `userpwd`, `cainfo` and adds it to requests as well as headers. May I try to create a PR for this?

**Comment by onurfiliz** [comment]
Those are valid concerns. Does using `httr::with_config` alleviate them? Something like:

    auth_wrapper <- function(f) {
      return(
        function(...) {
          httr::with_config(
            httr::config(userpwd=""),
            f(...)
          )
        }
      )
    }
    dbConnect <- auth_wrapper(DBI::dbConnect)
    dbGetQuery <- auth_wrapper(DBI::dbGetQuery)

By leveraging a variant of this approach to e.g. choose what configuration to set using the host value of the arguments, you can implement a quite flexible solution.

The reason I'm hesitant to add these to RPresto is somewhat in the spirit of 'separation of concerns'. These are mainly http communication related configurations, so it's cleaner to keep them in the httr realm. Besides, the longer we can stay away from locking in to a particular authorization mechanism the better, since it can (and it indeed did, internally at Facebook) change with additions to Presto.

That said, it would be interesting to see how you would design such an API. Before creating a PR, it would be helpful to discuss what the call to dbConnect(?) would look like, especially when we consider potential authorization options beyond this particular setting.

**Comment by yutannihilation** [comment]
Thanks, we can use `httr::with_config()` definitely.

> Before creating a PR, it would be helpful to discuss what the call to dbConnect(?) would look like, especially when we consider potential authorization options beyond this particular setting.

I just thought it's nice to just support Basic auth with new arg `password`, and `cainfo`.

``` r
dbConnect(..., password = "...", cainfo = "...")
```

If we support multiple authentications, maybe we can use `auth_type`? If `auth_type` is not `NULL`, `PrestoConnection` can store `httr::authenticate(user, password, type = auth_type)`.

``` r
# no auth (default)
dbConnect(..., password = "...", cainfo = "...", auth_type = NULL)

# basic
dbConnect(..., password = "...", cainfo = "...", auth_type = "basic")

# GSS Negotiate (SPNEGO), probably for Kerberos auth
dbConnect(..., password = "...", cainfo = "...", auth_type = "gssnegotiate")
```

**Comment by onurfiliz** [comment]
Hmm, this may be a somewhat limiting approach. See for instance #103, where a header is used for authentication. Internally, we rely on an environment variable pointing to a certificate. Let's keep it as is for now, until the wrapping approach is not sufficient and/or Presto settles on a canonical solution.

**Comment by yutannihilation** [comment]
Ah, I forgot about that. But, since both `httr::authenticate()` and `httr::add_headers()` are just `httr::config()`, I think you can just change `.request_headers()` to something like `.request_config()`.

```r
.request_config <- function(conn) {
  headers <- httr::add_headers(
    "X-Presto-User"= conn@user,
    "X-Presto-Catalog"= conn@catalog,
    "X-Presto-Schema"= conn@schema,
    "X-Presto-Source"= conn@source,
    "X-Presto-Time-Zone" = conn@session.timezone,
    "User-Agent"= getPackageName(),
    "X-Presto-Session"=conn@session$parameterString()
  )
  # authenticate can be NULL
  return(c(headers, conn@httr_authenticate))
}
```

(If we need to consider the case when the Presto user and LDAP user are different, the implementation might be a bit complicated)

If this seems not convincing to you, I'm OK to ignore. But, please add the documentation about using wrapper. Currently, it's too hard for ordinary users to use RPresto with LDAP authentication. I'm very tired to recommend RJDBC, which I'm not a big fan of, for this reason....

**Comment by electrum** [comment]
Quick note, from a client perspective, this is simply username/password auth. LDAP is a server side configuration detail. It’s actually pluggable, so the server could use something other than LDAP to validate the credentials:  https://prestodb.io/docs/current/develop/password-authenticator.html
